#!/bin/bash

# Export PREFIX with a custom directory or use default one.
if [ -z "$PREFIX" ]; then
	PREFIX="/usr/local/bin/"
fi

install_oil() {

	if [ `which sudo` ]; then
		sudo sh -c "curl --silent http://get.fuelphp.com/installer.sh > ${PREFIX}oil"
		sudo chmod +x ${PREFIX}oil
	else
		sh -c "curl --silent http://get.fuelphp.com/installer.sh > ${PREFIX}oil"
		chmod +x ${PREFIX}oil
	fi
}

#
# Handle execution
#
main() {
	# Start installation
	install_oil
	exit 0
}

main
